---
title: Report
author: Atticus Tarleton
date: today
description: Data Analysis and Final Report
jupyter: python3
execute:
  eval: true
format:
  html: default
  pdf: default
---

The below code sets the project root to the right location, making file paths easier to manage
```{python}
import os
from pathlib import Path

_project_root = Path.cwd()
while not (_project_root / ".git").exists():
    _project_root = _project_root.parent
    if _project_root == _project_root.parent:
        raise RuntimeError(".git not found — are you inside the repo?")
os.chdir(_project_root)
print(os.getcwd())
```

## Creating the database and some more data engineering

The below code block is going to create a database connection to the large and small clean healthcare databases made in the engineering.qmd file
```{python}
import duckdb

con = duckdb.connect()
con.execute(f"""
  CREATE OR REPLACE TABLE small_healthcare AS
  SELECT * FROM read_parquet('{"Data/clean_data/small_2024_health_data.parquet"}')
""")
con.execute(f"""
  CREATE OR REPLACE TABLE large_healthcare AS
  SELECT * FROM read_parquet('{"Data/clean_data/large_2024_health_data.parquet"}')
""")
con.execute(f"""
  CREATE OR REPLACE TABLE small_combined_healthcare AS
  SELECT * FROM read_parquet('{"Data/clean_data/small_2024_health_data.parquet"}')
  WHERE st_abbrev = 'VT' OR st_abbrev = 'US'
""")
```

Questions to answer
1) How does Vermont's ratios of health care professions look compared to the US as a whole
	- graph 1: Bar plot of ratio of vermont next to US ratio
		- will need to do some pivoting of data and such
	- graph 2: do the same as above, but instead by summing the northeast region
	    - how does vermont compare to the local region
	    - questions:
	        - include vermont or not?
	        - take the ratios of each state and average them, or sum the states values and average them?
2) States with the most physicians, and their total population
    - basically, do the numbers align
    - and do the same with the least physicians
3) States with the greatest ratio of physicians, and with the smallest ratio

This code chunk below sets up the datasets that will be plotted and used in the future
```{python}
import pandas as pd

small_health_df = pd.read_parquet('Data/clean_data/small_2024_health_data.parquet')
large_health_df = pd.read_parquet('Data/clean_data/large_2024_health_data.parquet')

occupation_count_columns = small_health_df.columns[2:35].tolist()

small_ratio_df = small_health_df.copy()
for i in occupation_count_columns:
    small_ratio_df[i] = small_ratio_df[i]/small_ratio_df['popn_pums_23']

small_combined_ratio_df = small_ratio_df[(small_ratio_df['st_abbrev'] == 'VT') | (small_ratio_df['st_abbrev'] =='US')]

small_combined_ratio_melted = small_combined_ratio_df.melt(id_vars='st_abbrev',
                    value_vars=occupation_count_columns,
                    var_name='occupation', value_name='ratio')

# to find columns with nan values so they can be removed
with pd.option_context('display.max_columns', None):
    print(small_health_df[(small_health_df['st_abbrev'] != 'VT') & (small_health_df['region'] =='NE')])
    #columns with nan values: podtrst, chiro, opto, dietn, pharm_aide, med_transcrp, vetin_asst, phleb,

occupation_count_columns_ne = occupation_count_columns
occupation_count_columns_ne.remove('podtrst_23')
occupation_count_columns_ne.remove('chiro_23')
occupation_count_columns_ne.remove('opto_23')
occupation_count_columns_ne.remove('dietn_23')
occupation_count_columns_ne.remove('pharm_aide_23')
occupation_count_columns_ne.remove('med_transcrp_23')
occupation_count_columns_ne.remove('vetin_asst_23')
occupation_count_columns_ne.remove('phleb_23')

ne_without_vt_sum_df = small_health_df[(small_health_df['st_abbrev'] != 'VT') & (small_health_df['region'] =='NE')].sum()
vt_only_df = small_health_df.iloc[45]
ne_without_vt_sum_df['st_abbrev'] = 'NE'
ne_without_vt_sum_df['region'] = 'NE'
ne_without_vt_sum_df['fips_st'] = '-99' #representing a null value
vt_and_ne_df = pd.DataFrame([vt_only_df, ne_without_vt_sum_df])
vt_and_ne_df = vt_and_ne_df.reset_index().drop('index', axis=1)

vt_and_ne_ratio_df = vt_and_ne_df.copy()
for i in occupation_count_columns:
    vt_and_ne_ratio_df[i] = vt_and_ne_ratio_df[i]/vt_and_ne_ratio_df['popn_pums_23']

vt_and_ne_ratio_melted = vt_and_ne_ratio_df.melt(id_vars='st_abbrev',
                    value_vars=occupation_count_columns,
                    var_name='occupation', value_name='ratio')
```

## Exploratory Data Analysis

The code chunk below answers the question of which states have the most physicians, and which ones have the least using Pandas
```{python}
physician_sorted_df = small_health_df.drop(51).sort_values(by='phys_wkforc_23', ascending=False)[['st_abbrev', 'phys_wkforc_23', 'popn_pums_23']]
print("\n the 10 states with the most physicians")
display(physician_sorted_df.head(10))
print("\nthe 10 states with the fewest physicians")
display(physician_sorted_df.tail(10))
```

The code chunk below answers the of which states have the most physicians, and which ones have the least using SQL
```{python}
print("\n the 10 states with the most physicians")
display(con.execute("""SELECT st_abbrev, phys_wkforc_23, popn_pums_23
    FROM small_healthcare WHERE st_abbrev != 'US'
    ORDER BY phys_wkforc_23 DESC LIMIT 10""").df())

print("\n the 10 states with the fewest physicians")
display(con.execute("""SELECT st_abbrev, phys_wkforc_23, popn_pums_23
    FROM small_healthcare WHERE st_abbrev != 'US'
     ORDER BY phys_wkforc_23 LIMIT 10""").df())
```

The code chunk below answers the question of what states have the largest and smallest ratio of health care professionals using Pandas
```{python}
small_ratio_df.sort_values(by='phys_wkforc_23', ascending=False)[['st_abbrev', 'phys_wkforc_23', 'popn_pums_23']]
```

The code chunk below answers the question of what states have the largest and smallest ratio of health care professionals using SQL
```{python}
con.execute("ALTER TABLE small_healthcare ADD phys_wkforc_ratio_23 FLOAT")
con.execute("UPDATE small_healthcare SET phys_wkforc_ratio_23 = phys_wkforc_23/popn_pums_23")
display(con.execute("SELECT st_abbrev, phys_wkforc_ratio_23, popn_pums_23 FROM small_healthcare ORDER BY phys_wkforc_ratio_23 DESC").df())
```

## Plotting
The goal of this section is to now dive into how Vermont compares to the United States, as well as other states like Vermont




The code chunk below does the plotting for the first plot

What this plot is supposed to show is the ratio of different workers in different health care professions in Vermont compared to the US as a whole. This will be helpful in understanding how Vermont's healthcare system compares to the US.


```{python}
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 5))
plt.xticks(rotation=90)
sns.barplot(data=small_combined_ratio_melted, x='occupation', y='ratio', hue='st_abbrev')
plt.title("Bar Plot Comparing the Ratio of Different Kinds of Health Care Professionals to the\nTotal Population for Vermont and the United States")
plt.show()
```

Looking at the plot now, we see that Vermont has more physicians than the US on average, and tends to have a slightly higher ratio of health professionals in general.
While there are a number of professions where there is no blue bar, this is because there was no data collected for those professions, rather than there being basically no one practicing them.
Besides the fact that the professions with no data in Vermont are generally the least numerous professions, I know that at least some of the lack of data is because it is not collected not that there is no one practicing those professions, as one bar with no data is ot_23, standing for occupational therapist and I know there are occupational therapists currently practicing in Vermont.




The code chunk below does the plotting for the second plot

```{python}
plt.figure(figsize=(12, 5))
plt.xticks(rotation=90)
sns.barplot(data=vt_and_ne_ratio_melted, x='occupation', y='ratio', hue='st_abbrev')
plt.title("Bar Plot Comparing the Ratio of Different Kinds of Health Care Professionals to the\nTotal Population for Vermont and the Rest of the Northeast")
plt.show()
```
This plot takes looking at the whole of the United States, and narrows it down to the rest of the northeast. This means that Vermont
is being compared to similar states, namely Connecticut, Maine, Massachusetts, New Hampshire, and Rhode Island. This was done by adding the
the profession numbers as well as the populations of those states together, and dividing the profession numbers by the summed population to get a ratio of professionals
to population for the entire Northeast leaving out Vermont. Vermont is left out because there are not too a lot of states in the Northeast, and if Vermont was left in, its
numbers would skew the Northeast average closer to Vermont's, and the goal here is not to find the northeast average, but to compare Vermont's health care profession ratio's
to other similar states.

Looking at the results, we can see that Vermont and the other Northeast States are pretty similar. For most of the ratio's, we can see that the other Northeast States have on
average slightly more health-care professionals compared to their total population. That being said, Vermont does have a substantially larger ratio of
counselors and personal care aides, as well as slightly more social workers, repository therapists, speech pathologists, and massage therapists.

## Conclusion
In conclusion, Vermont is similar to the rest of the Northeast when it comes to the ratio of health care professionals to its total population.
That being said, the Northeast as a whole has a larger ratio of health professionals to its population, and Vermont tends to have ratios greater than
the United States as a whole.

If your looking for something surprising, the amount of counselors Vermont has is quite surprising, with its ratio being about double the ratio that the United States had.
Beyond that, there was nothing too surprising in the data to me as a non-expert, though if you are an expert some of the numbers might be more shocking.

While I am wrapping up this project right now, if I have more time to devote to this then doing analysis on the cosine similarly of and k-means clustering on the ratio's of health professions between
states would be interesting. I picked the Northeast region as a whole when looking for other states that are similar to Vermont, but it would be interesting seeing what the data actually says
about which states are similar.