---
title: Wastewater Report
author: Atticus Tarleton
date: today
description: Data Analysis and Report for Vermont Wastewater Data
jupyter: python3
execute:
  eval: true
format:
  html: default
  pdf: default
---

```{python}
import pandas as pd
import geopandas as gpd
```

The below code sets the project root to the right location, making file paths easier to manage
```{python}
import os
from pathlib import Path

_project_root = Path.cwd()
while not (_project_root / ".git").exists():
    _project_root = _project_root.parent
    if _project_root == _project_root.parent:
        raise RuntimeError(".git not found — are you inside the repo?")
os.chdir(_project_root)
print(os.getcwd())
```

Creating paths to the data
```{python}
data_path = Path("../react-vt-data/backend/Data/_Processed/wastewater")
soil_path = data_path / "soil_suitability"
treatment_path = data_path / "treatment_facilities"
service_path = data_path / "service_areas"
```

## Soil Suitability analysis


Reading in the data
```{python}
info_ACRPC = pd.read_parquet(soil_path/"info_ACRPC_Soil_Septic.parquet")
info_BCRC = pd.read_parquet(soil_path/"info_BCRC_Soil_Septic.parquet")
info_CCRPC = pd.read_parquet(soil_path/"info_CCRPC_Soil_Septic.parquet")
info_CVRPC = pd.read_parquet(soil_path/"info_CVRPC_Soil_Septic.parquet")
info_LCPC = pd.read_parquet(soil_path/"info_LCPC_Soil_Septic.parquet")
info_MARC = pd.read_parquet(soil_path/"info_MARC_Soil_Septic.parquet")
info_NWRPC = pd.read_parquet(soil_path/"info_NWRPC_Soil_Septic.parquet")

geom_ACRPC = gpd.read_parquet(soil_path/"geom_ACRPC_Soil_Septic.parquet")
geom_BCRC = gpd.read_parquet(soil_path/"geom_BCRC_Soil_Septic.parquet")
geom_CCRPC = gpd.read_parquet(soil_path/"geom_CCRPC_Soil_Septic.parquet")
geom_CVRPC = gpd.read_parquet(soil_path/"geom_CVRPC_Soil_Septic.parquet")
geom_LCPC = gpd.read_parquet(soil_path/"geom_LCPC_Soil_Septic.parquet")
geom_MARC = gpd.read_parquet(soil_path/"geom_MARC_Soil_Septic.parquet")
geom_NWRPC = gpd.read_parquet(soil_path/"geom_NWRPC_Soil_Septic.parquet")
```

making a plot to see the geometry data
```{python}
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(10, 10))

geom_ACRPC.plot(ax=ax, color='lightgray')
geom_BCRC.plot(ax=ax, color='blue')
geom_CCRPC.plot(ax=ax, color='purple')
geom_CVRPC.plot(ax=ax, color='green')
geom_LCPC.plot(ax=ax, color='orange')
geom_MARC.plot(ax=ax, color='yellow')
geom_NWRPC.plot(ax=ax, color='red')

plt.show()
```
What this plot shows is that we do not have all of the soil suitability data. We are missing some of Northeastern Vermont,
Central Vermont, and a bit of Southeastern Vermont as well. While there is still a lot of data available, this merits
future research to see if there is soil suitability data available for the regional planning commissions that we don't
have data for.



getting the amount of each soil suitability level for each regional planning commission
```{python}
import numpy as np


info_soil_data = [info_ACRPC, info_CCRPC, info_CVRPC, info_LCPC, info_MARC, info_NWRPC, info_BCRC]
whole_vermont_info = pd.concat(info_soil_data, ignore_index=True)
info_soil_data.append(whole_vermont_info)
info_soil_data_name = ["ACRPC", "CCRPC", "CVRPC", "LCPC", "MARC", "NWRPC", "BCRC", "Vermont"]

for i in range(len(info_soil_data)):
    # print(info_soil_data[i].sort_values(by='Suitability').groupby(['Suitability'])['Acres'].sum())
    # print(np.sort(info_soil_data[i]['Suitability'].unique()))
    plt.bar(height = info_soil_data[i].sort_values(by='Suitability').groupby(['Suitability'])['Acres'].sum(), x = np.sort(info_soil_data[i]['Suitability'].unique()))
    plt.xticks(rotation = 45)
    plt.title(f"Soil Suitability Distribution by Acres for {info_soil_data_name[i]}")
    plt.xlabel("Soil Suitability Level")
    plt.ylabel("Number of Acres")
    plt.show()

whole_vermont_info = pd.concat(info_soil_data, ignore_index=True)
```
What these charts are going over is the number of acres of each level of soil suitability for septic tanks for each
regional planning commission, as well as Vermont as a whole. There is an important caveat that the Vermont section is not
all of Vermont, but rather all of the data we have, as there are a few regional planning commissions who's data we don't
have.

What these charts show is that there is a lot of variability between regions in terms of the distribution of soil suitability.
By this I mean that some regional planning commissions have radically different soil suitabilities, with one example being
that the NWRCP has 'not suited' as by far its largest soil suitability level, while for BCRC 'moderately suited' is its
largest soil suitability level, with 'not suited' coming in a distant second.

Looking a Vermont as a whole, either 'not suited' or 'moderately suited' is the largest soil suitability level for most
regions, though CVRCP bucks that trend with 'marginally suited' being its most common soil suitability level. This frequency
is shown on the Vermont total numbers, with 'not suited' being the most common soil suitability level, 'moderately suited'
being the next most common, and 'marginally suited' being a close third. While the top 3 are all pretty close in terms of
acres, the other two, 'not rated' and 'well suited', have a lot fewer acres. What this means for Vermont as a whole is a
lot of its land is not really suited for septic tanks between all the acres that are 'not suited' or 'marginally suited'.
After that a good amount of land is 'moderately suitable', indicating that septic tanks could be placed there, though
conditions are not perfect for it. And lastly, there is a relatively small percentage of land that is 'well suited', and
no regions have 'well suited' as their top two most common soil suitability levels, indicating that no region of Vermont
is perfect for septic systems.



## Wastewater Treatment Facilities

Reading in the data
```{python}
treatment_geom = gpd.read_parquet(treatment_path/"treatment_facility_geom.parquet")
treatment_info = pd.read_parquet(treatment_path/"treatment_facility_info.parquet")
permit_info = pd.read_parquet(treatment_path/"treatment_facility_permit_info.parquet")
miscellaneous_info = pd.read_parquet(treatment_path/"treatment_facility_miscellaneous_info.parquet")
```
Seeing whats in the data
```{python}
display(treatment_geom.head())
display(treatment_info.head())
display(permit_info.head())
display(miscellaneous_info.head())
```

Getting summary statistics from the treatment_info table
```{python}
print(treatment_info.groupby(['RPC'])['SeptageReceivedAtThisFacility'].value_counts())
```
```{python}
treatment_info['DesignHydraulicCapacityInMGD'] = pd.to_numeric(treatment_info['DesignHydraulicCapacityInMGD'], errors='coerce')
print(f"the average DesignHydraulicCapacityInMGD: {treatment_info['DesignHydraulicCapacityInMGD'].mean()}")
```


Plotting the geometry data
```{python}
fig, ax = plt.subplots(figsize=(8, 6))

treatment_geom.plot(ax=ax, color='red', markersize=20)
plt.show()
```
What this plot shows is that there are a lot of wastewater treatment facilities, distributed relatively evenly throughout
Vermont. However, while the distribution is spread pretty evenly throughout Vermont, there is a lower density of treatment
facilities in Northeastern Vermont.



Putting the two maps together, so you can see the boundaries of the Regional planning districts,
and where their wastewater treatment facilities are
```{python}
fig, ax = plt.subplots(figsize=(10, 10))

geom_ACRPC.plot(ax=ax, color='lightgray')
geom_BCRC.plot(ax=ax, color='blue')
geom_CCRPC.plot(ax=ax, color='purple')
geom_CVRPC.plot(ax=ax, color='green')
geom_LCPC.plot(ax=ax, color='orange')
geom_MARC.plot(ax=ax, color='yellow')
geom_NWRPC.plot(ax=ax, color='red')
treatment_geom.plot(ax=ax, color='white', markersize=20, edgecolor='black')

ax.set_xlabel("Latitude")
ax.set_ylabel("Longitude")


plt.show()
```
What this plot combines is the soil suitability data we do have with the the location of wastewater treatment facilities.
This highlights the lack of wastewater treatment facilites in the Northeast and Central-East of Vermont as well as the
lack of soil suitability data there as well. Any missing data for soil suitability is not idea, but it is only compounded
by the likely lack of options other than septic tanks, which our soil suitability data provides insight about


## Wastewater Service Areas

reading in the data
```{python}
service_geom = gpd.read_parquet(service_path/"service_area_geom.parquet")
service_info = pd.read_parquet(service_path/"service_area_info.parquet")
service_miscellaneous_info = pd.read_parquet(service_path/"service_area_miscellaneous_info.parquet")
```

now to take a look at the datasets
```{python}
display(service_geom.head())
display(service_info.head())
display(service_miscellaneous_info.head())
```

now to make some graphs
```{python}
service_geom.plot(color = 'violet')
plt.show()
```
What this plot shows is that there is not a lot of space overall in Vermont that is covered by wastewater service areas.
Also, while the space covered by wastewater service areas is spread pretty evenly throughout Vermont, there is a lower
density of service areas in Northeastern Vermont.

```{python}
fig, ax = plt.subplots(figsize=(12, 10))

service_geom.plot(ax=ax, color='violet')
treatment_geom.plot(ax=ax, color='white', markersize=1, edgecolor='white')
ax.set_title("Plot of wastewater treatment facilities and wastewater service areas")
ax.set_xlabel("Latitude")
ax.set_ylabel("Longitude")

plt.show()
```
What this plot shows is that the wastewater treatment service areas do line up with wastewater treatment facilities.
That being said, the service areas don't line up perfectly with the treatment facilities, most notably in that there are
a number of treatment facilities that don't seem to have an associated service area. This could be a gap in our service
area data, or it could be that the treatment facilities include kinds of wastewater facilities that don't serve the general
populus. This is an area that needs to be looked in to more, to see if there are data holes.


```{python}
fig, ax = plt.subplots(figsize=(12, 10))

geom_ACRPC.plot(ax=ax, color='lightgray')
geom_BCRC.plot(ax=ax, color='blue')
geom_CCRPC.plot(ax=ax, color='purple')
geom_CVRPC.plot(ax=ax, color='paleturquoise')
geom_LCPC.plot(ax=ax, color='green')
geom_MARC.plot(ax=ax, color='yellow')
geom_NWRPC.plot(ax=ax, color='lightcyan')
service_geom.plot(ax=ax, color='violet')
treatment_geom.plot(ax=ax, color='white', markersize=10, edgecolor='black')

ax.set_title("Plot of RPCs that we have data on, treatment facilities, and wastewater service areas")
ax.set_xlabel("Latitude")
ax.set_ylabel("Longitude")

plt.show()
```
What this plot shows is how the wastewater treatment service areas and facilities line up with the septic tank soil
suitability data that we have. And what this shows is a critical lack of data for septic tank soil suitability for
Northeast Vermont. Northeast Vermont, as identified by earlier graphs, is one of the locations in Vermont with the lowest
density of wastewater treatment service areas to its total land, and so the lack of information about suitability for
septic tanks, which are an alternative to a public sewage systems which is represented by the wastewater treatment service
areas.